# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labelme.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(950, 655)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(140, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(140, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 138, 590))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.pushButton_Open = QtGui.QPushButton(self.scrollAreaWidgetContents)
        #self.pushButton_Open = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.pushButton_Open.setGeometry(QtCore.QRect(0, 0, 141, 81))
        self.pushButton_Open.setObjectName(_fromUtf8("pushButton_Open"))
        self.pushButton_NextImage = QtGui.QPushButton(self.scrollAreaWidgetContents)
        #see.pushButton_NextImage = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.pushButton_NextImage.setGeometry(QtCore.QRect(0, 80, 141, 81))
        self.pushButton_NextImage.setObjectName(_fromUtf8("pushButton_NextImage"))
        self.pushButton_PrevImage = QtGui.QPushButton(self.scrollAreaWidgetContents)
        #elf.pushButton_PrevImage = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        self.pushButton_PrevImage.setGeometry(QtCore.QRect(0, 160, 141, 91))
        self.pushButton_PrevImage.setObjectName(_fromUtf8("pushButton_PrevImage"))
        self.pushButton_Save = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Save.setGeometry(QtCore.QRect(0, 250, 141, 91))
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.pushButton_Create = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Create.setGeometry(QtCore.QRect(0, 340, 141, 91))
        self.pushButton_Create.setObjectName(_fromUtf8("pushButton_Create"))
        self.pushButton_Delete = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Delete.setGeometry(QtCore.QRect(0, 430, 141, 91))
        self.pushButton_Delete.setObjectName(_fromUtf8("pushButton_Delete"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        '''self.scrollArea_2 = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))'''
        self.label_Image = QtGui.QLabel(self.centralwidget)
        self.label_Image.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_Image.setMinimumSize(QtCore.QSize(0, 0))
        self.label_Image.setMaximumSize(QtCore.QSize(3000, 16777215))
        #self.label_Image.setWidgetResizable(True)
        self.label_Image.setObjectName(_fromUtf8("label_Image"))
        self.gridLayout.addWidget(self.label_Image, 0, 1, 1, 1)
        self.scrollArea_3 = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 198, 590))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        #elf.toolButton_Config = QtGui.QToolButton(self.scrollAreaWidgetContents_3)
        self.toolButton_Config= QtGui.QCommandLinkButton(self.scrollAreaWidgetContents_3)
        self.toolButton_Config.setGeometry(QtCore.QRect(20, 10, 121, 51))
        self.toolButton_Config.setObjectName(_fromUtf8("toolButton_Config"))
        self.label_ColorChoose = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_ColorChoose.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_ColorChoose.setObjectName(_fromUtf8("label_ColorChoose"))
        #self.label_Category1 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category_list = []
        self.label_Category1 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        #self.label_Category1.setGeometry(QtCore.QRect(20, 200, 54, 16))
        self.label_Category1.setGeometry(QtCore.QRect(20, 130, 54, 16))
        self.label_Category1.setObjectName(_fromUtf8("label_Category1"))
        self.label_Category1.setVisible(False)
        self.label_Category_list.append(self.label_Category1)
        #self.label_Category2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category2 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category2.setGeometry(QtCore.QRect(20, 170, 90, 16))
        self.label_Category2.setObjectName(_fromUtf8("label_Category2"))
        self.label_Category2.setVisible(False)
        self.label_Category_list.append(self.label_Category2)
        #self.label_Category3 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category3 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category3.setGeometry(QtCore.QRect(20, 210, 54, 16))
        self.label_Category3.setObjectName(_fromUtf8("label_Category3"))
        self.label_Category3.setVisible(False)
        self.label_Category_list.append(self.label_Category3)
        #self.label_Category4 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category4 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category4.setGeometry(QtCore.QRect(20, 250, 90, 16))
        self.label_Category4.setObjectName(_fromUtf8("label_Category4"))
        self.label_Category4.setVisible(False)
        self.label_Category_list.append(self.label_Category4)
        #self.label_Category5 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category5 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category5.setGeometry(QtCore.QRect(20, 290, 54, 16))
        self.label_Category5.setObjectName(_fromUtf8("label_Category5"))
        self.label_Category5.setVisible(False)
        self.label_Category_list.append(self.label_Category5)
        #self.label_Category6 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category6 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category6.setGeometry(QtCore.QRect(20, 330, 54, 16))
        self.label_Category6.setObjectName(_fromUtf8("label_Category6"))
        self.label_Category6.setVisible(False)
        self.label_Category_list.append(self.label_Category6)
        #self.label_Category7 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category7 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category7.setGeometry(QtCore.QRect(20, 370, 54, 16))
        self.label_Category7.setObjectName(_fromUtf8("label_Category7"))
        self.label_Category7.setVisible(False)
        self.label_Category_list.append(self.label_Category7)
        #self.label_Category8 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category8 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category8.setGeometry(QtCore.QRect(20, 410, 54, 16))
        self.label_Category8.setObjectName(_fromUtf8("label_Category8"))
        self.label_Category8.setVisible(False)
        self.label_Category_list.append(self.label_Category8)
        self.label_Category9 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category9.setGeometry(QtCore.QRect(20, 450, 54, 16))
        self.label_Category9.setObjectName(_fromUtf8("label_Category9"))
        self.label_Category9.setVisible(False)
        self.label_Category_list.append(self.label_Category9)
        self.label_Category10 = QtGui.QRadioButton(self.scrollAreaWidgetContents_3)
        self.label_Category10.setGeometry(QtCore.QRect(20, 490, 54, 16))
        self.label_Category10.setObjectName(_fromUtf8("label_Category10"))
        self.label_Category10.setVisible(False)
        self.label_Category_list.append(self.label_Category10)
        self.label_color_list = []
        self.label_Category1_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category1_color.setGeometry(QtCore.QRect(120, 130, 54, 16))
        self.label_Category1_color.setObjectName(_fromUtf8("label_Category1_color"))
        self.label_color_list.append(self.label_Category1_color)
        self.label_Category2_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category2_color.setGeometry(QtCore.QRect(120, 170, 54, 16))
        self.label_Category2_color.setObjectName(_fromUtf8("label_Category2_color"))
        self.label_color_list.append(self.label_Category2_color)
        self.label_Category3_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category3_color.setGeometry(QtCore.QRect(120, 210, 54, 16))
        self.label_Category3_color.setObjectName(_fromUtf8("label_Category3_color"))
        self.label_color_list.append(self.label_Category3_color)
        self.label_Category4_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category4_color.setGeometry(QtCore.QRect(120, 250, 54, 16))
        self.label_Category4_color.setObjectName(_fromUtf8("label_Category4_color"))
        self.label_color_list.append(self.label_Category4_color)
        self.label_Category5_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category5_color.setGeometry(QtCore.QRect(120, 290, 54, 16))
        self.label_Category5_color.setObjectName(_fromUtf8("label_Category5_color"))
        self.label_color_list.append(self.label_Category5_color)
        self.label_Category6_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category6_color.setGeometry(QtCore.QRect(120, 330, 54, 16))
        self.label_Category6_color.setObjectName(_fromUtf8("label_Category6_color"))
        self.label_color_list.append(self.label_Category6_color)
        self.label_Category7_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category7_color.setGeometry(QtCore.QRect(120, 370, 54, 16))
        self.label_Category7_color.setObjectName(_fromUtf8("label_Category7_color"))
        self.label_color_list.append(self.label_Category7_color)
        self.label_Category8_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category8_color.setGeometry(QtCore.QRect(120, 410, 54, 16))
        self.label_Category8_color.setObjectName(_fromUtf8("label_Category8_color"))
        self.label_color_list.append(self.label_Category8_color)
        self.label_Category9_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category9_color.setGeometry(QtCore.QRect(120, 450, 54, 16))
        self.label_Category9_color.setObjectName(_fromUtf8("label_Category9_color"))
        self.label_color_list.append(self.label_Category9_color)
        self.label_Category10_color = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_Category10_color.setGeometry(QtCore.QRect(120, 490, 54, 16))
        self.label_Category10_color.setObjectName(_fromUtf8("label_Category10_color"))
        self.label_color_list.append(self.label_Category10_color)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuThsfh = QtGui.QMenu(self.menubar)
        self.menuThsfh.setObjectName(_fromUtf8("menuThsfh"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen.setShortcut('Ctrl+O')
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave.setShortcut('Ctrl+S')
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionClose.setShortcut('Ctrl+E')
        self.actionCreate_Pixmap = QtGui.QAction(MainWindow)
        self.actionCreate_Pixmap.setObjectName(_fromUtf8("actionCreate_Pixmap"))
        self.actionCreate_Pixmap.setShortcut('Ctrl+C')
        self.actionEdit_Label = QtGui.QAction(MainWindow)
        self.actionEdit_Label.setObjectName(_fromUtf8("actionEdit_Label"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionDelete.setShortcut('Ctrl+D')
        self.menuThsfh.addSeparator()
        self.menuThsfh.addAction(self.actionOpen)
        self.menuThsfh.addAction(self.actionSave)
        self.menuThsfh.addAction(self.actionClose)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCreate_Pixmap)
        self.menuEdit.addAction(self.actionDelete)
        self.menubar.addAction(self.menuThsfh.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LableMe", None))
        self.pushButton_Open.setText(_translate("MainWindow", "Open", None))
        self.pushButton_NextImage.setText(_translate("MainWindow", "Next Image", None))
        self.pushButton_PrevImage.setText(_translate("MainWindow", "Prev Image", None))
        self.pushButton_Save.setText(_translate("MainWindow", "Save", None))
        self.pushButton_Create.setText(_translate("MainWindow", "Create Pixmap", None))
        self.pushButton_Delete.setText(_translate("MainWindow", "Delete Line", None))
        self.toolButton_Config.setText(_translate("MainWindow", "目标配置", None))
        self.label_ColorChoose.setText(_translate("MainWindow", "目标种类选择：", None))
        self.menuThsfh.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        #self.actionOpen_Dir.setText(_translate("MainWindow", "Open Dir", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionCreate_Pixmap.setText(_translate("MainWindow", "Create Pixmap", None))
        self.actionEdit_Label.setText(_translate("MainWindow", "Edit Label", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete Line", None))

